services:
  sqlite:
    image: keinos/sqlite3:latest
    container_name: pix-payments-sqlite
    volumes:
      - ./data:/data
    command: tail -f /dev/null
    networks:
      - pix-payments-network

networks:
  pix-payments-network:
    driver: bridge
