services:
  pgsql:
    image: postgres:latest
    container_name: pix-payments-postgres
    environment:
      POSTGRES_USER: pix_user
      POSTGRES_PASSWORD: pix_password
      POSTGRES_DB: pix_payments
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - pix-payments-network
  dbgate:
    image: dbgate/dbgate
    restart: always
    container_name: pix-payments-dbgate
    ports:
      - "3000:3000"
    volumes:
      - dbgate_data:/root/.dbgate
    networks:
      - pix-payments-network
    depends_on:
      - pgsql

volumes:
  dbgate_data:
    driver: local

networks:
  pix-payments-network:
    driver: bridge
